language: node_js
node_js: 8

cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY_SECRET
    bucket: $AWS_BUCKET_PROD
    skip_cleanup: true
    local_dir: build
    on:
      branch: stable
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY_SECRET
    bucket: $AWS_BUCKET_BETA
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
