language: node_js
node_js: 8

cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  - provider: s3
    access_key_id:
      secure: "SM5uYup2CVi6sdNEleXi5TD4j+2Cw5T/dRo0HpIk36PijzAiEJH5oA2vJGwRTrXXmMLVAYWULEz2COXcY6A2Eka5/THeuvnVgpPxOK4ktgaOFUlyy2dpItSjn6G3ld3gE90dHUm/FYfX9PIVv0NeVnlWvj5PxzPfQ+DsXsEQ+CSNbRDOeC2QToIXgqx+aDNymIe6NcWC3LQR+kdh3I7an/07SrmZOhZCWZVYk63iChvv/ACSDy3StgaJZUefy0eUYfk4BKcZefAd9A0++pOTXFeriHv3z8t3GuWMqtwMPPYi5Ism71ipZxMLoGH8vdyAQPRvTQaSsF/srbBqeUpbpgvei0kE3co68hyI7KCmd95otfQJvUnQavTW9nRGsZEWqyQvTG24DCJJD2Pfj/jp2kfqdhjXmepAoCIN1btnIJ+OZFrGc0mQhhg3NiiRU070cwFzPKav799NAv6rR5CVzQFclhuK541fDMUWS4RDNRmqorfA1l5xJCdUNKWIMZlut+W3ehkRUacdlAG9M2b1lairvGqtg7OFOq8e1By68DMNKnoNLr07fCbO+b4WaT7cS185cSW8pURtSqXzxOiCKWKuGzzactsxuryN1QGr88hCuQ58U/tvZkgTAofFlvBPTsel+c9bWolq4Hjtl3j6xHk2fX7d9vrpzEV5d7RglqA="
    secret_access_key:
      secure: "Flx0yOsEXcgl/C46QV2sxLHkpMO+eF2c3GGIT3Am16U/ZXRhn48ymoBUwbH9qEqbP8jgDLEgdC2dJhawsJDS7QeitCSo3lnzxbGS6DDrWJ1fa+8J3egDJRLJvtjtCh8/aB6rgsKHtbc3z8eGoTv2xilt06wWojONkJ61BfY6Sy10LYt8MamfwDIGqNTUG/XU5hoVpavyKOVqgryQkZ23LQNdJnXD+I3NvOlRJQA7rkBxG/Ktb0Z7rKq0G3t/qtg67ood3KsNdg/h3kaAvn+vs/X+w2ZQr8XGm3AfleYN0dyd4yTNLzXmsjQhGo6tal8nLprQ0YoV6vHPQrqzaUMfWB49Ig13URZfT2MnXbD1s8C4SvxN4XjyHmealDzpGdAtAi8F+n39nNFCifKSXw1xHSmeCTon8GDCYD0ZZSgnTYHX4rZlI+FbJb7271oNYIjky0C3DMXFiMbxaqznURBLsy+NczFxQSXOpUurD2augO7SVCslJ/zU1oRgK2ajwJ1n6QebPoOCr6zDKvfELACWH5xb+PKkI2fGgttmD5xDy/vTRJzw+igXxNsL+iyq69khKbfYqD0jj2YO7Q9VUnRjPlL8W5EGcqri6u6f4KiWNXfkbrngWXmeS4109NPxiL0/TUSSa/eVGVyW80noGTJ9PF5jntU1RZa5kQy9CfXH+9M="
    bucket: kartograf.io
    skip_cleanup: true
    acl: public_read
    local_dir: packages/webui/build
    on:
      branch: stable
  - provider: s3
    access_key_id:
      secure: "SM5uYup2CVi6sdNEleXi5TD4j+2Cw5T/dRo0HpIk36PijzAiEJH5oA2vJGwRTrXXmMLVAYWULEz2COXcY6A2Eka5/THeuvnVgpPxOK4ktgaOFUlyy2dpItSjn6G3ld3gE90dHUm/FYfX9PIVv0NeVnlWvj5PxzPfQ+DsXsEQ+CSNbRDOeC2QToIXgqx+aDNymIe6NcWC3LQR+kdh3I7an/07SrmZOhZCWZVYk63iChvv/ACSDy3StgaJZUefy0eUYfk4BKcZefAd9A0++pOTXFeriHv3z8t3GuWMqtwMPPYi5Ism71ipZxMLoGH8vdyAQPRvTQaSsF/srbBqeUpbpgvei0kE3co68hyI7KCmd95otfQJvUnQavTW9nRGsZEWqyQvTG24DCJJD2Pfj/jp2kfqdhjXmepAoCIN1btnIJ+OZFrGc0mQhhg3NiiRU070cwFzPKav799NAv6rR5CVzQFclhuK541fDMUWS4RDNRmqorfA1l5xJCdUNKWIMZlut+W3ehkRUacdlAG9M2b1lairvGqtg7OFOq8e1By68DMNKnoNLr07fCbO+b4WaT7cS185cSW8pURtSqXzxOiCKWKuGzzactsxuryN1QGr88hCuQ58U/tvZkgTAofFlvBPTsel+c9bWolq4Hjtl3j6xHk2fX7d9vrpzEV5d7RglqA="
    secret_access_key:
      secure: "Flx0yOsEXcgl/C46QV2sxLHkpMO+eF2c3GGIT3Am16U/ZXRhn48ymoBUwbH9qEqbP8jgDLEgdC2dJhawsJDS7QeitCSo3lnzxbGS6DDrWJ1fa+8J3egDJRLJvtjtCh8/aB6rgsKHtbc3z8eGoTv2xilt06wWojONkJ61BfY6Sy10LYt8MamfwDIGqNTUG/XU5hoVpavyKOVqgryQkZ23LQNdJnXD+I3NvOlRJQA7rkBxG/Ktb0Z7rKq0G3t/qtg67ood3KsNdg/h3kaAvn+vs/X+w2ZQr8XGm3AfleYN0dyd4yTNLzXmsjQhGo6tal8nLprQ0YoV6vHPQrqzaUMfWB49Ig13URZfT2MnXbD1s8C4SvxN4XjyHmealDzpGdAtAi8F+n39nNFCifKSXw1xHSmeCTon8GDCYD0ZZSgnTYHX4rZlI+FbJb7271oNYIjky0C3DMXFiMbxaqznURBLsy+NczFxQSXOpUurD2augO7SVCslJ/zU1oRgK2ajwJ1n6QebPoOCr6zDKvfELACWH5xb+PKkI2fGgttmD5xDy/vTRJzw+igXxNsL+iyq69khKbfYqD0jj2YO7Q9VUnRjPlL8W5EGcqri6u6f4KiWNXfkbrngWXmeS4109NPxiL0/TUSSa/eVGVyW80noGTJ9PF5jntU1RZa5kQy9CfXH+9M="
    bucket: beta.kartograf.io
    skip_cleanup: true
    acl: public_read
    local_dir: packages/webui/build
    on:
      branch: master
